=== AndreaFalanti/popnas/src/config_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "search_space": {
            "type": "object",
            "properties": {
                "blocks": {
                    "type": "integer"
                },
                "lookback_depth": {
                    "type": "integer"
                },
                "operators": {
                    "type": "array",
                    "items": {"type": "string"}
                }
            },
            "required": [
                "blocks",
                "lookback_depth",
                "operators"
            ]
        },
        "search_strategy": {
            "type": "object",
            "properties": {
                "max_children": {
                    "type": "integer"
                },
                "max_exploration_children": {
                    "type": "integer"
                },
                "score_metric": {
                    "type": "string",
                    "enum": [
                        "accuracy",
                        "f1_score"
                    ]
                },
                "additional_pareto_objectives": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "time",
                            "params"
                        ]
                    }
                }
            },
            "required": [
                "max_children",
                "max_exploration_children",
                "score_metric",
                "additional_pareto_objectives"
            ]
        },
        "cnn_hp": {
            "type": "object",
            "properties": {
                "epochs": {
                    "type": "integer"
                },
                "learning_rate": {
                    "type": "number"
                },
                "filters": {
                    "type": "integer"
                },
                "weight_reg": {
                    "type": "number"
                },
                "use_adamW": {
                    "type": "boolean"
                },
                "drop_path_prob": {
                    "type": "number"
                },
                "cosine_decay_restart": {
                    "type": "object",
                    "properties": {
                        "enabled": {
                            "type": "boolean"
                        },
                        "period_in_epochs": {
                            "type": "integer"
                        },
                        "t_mul": {
                            "type": "number"
                        },
                        "m_mul": {
                            "type": "number"
                        },
                        "alpha": {
                            "type": "number"
                        }
                    },
                    "required": [
                        "enabled",
                        "period_in_epochs",
                        "t_mul",
                        "m_mul",
                        "alpha"
                    ]
                },
                "softmax_dropout": {
                    "type": "number"
                }
            },
            "required": [
                "epochs",
                "learning_rate",
                "filters",
                "weight_reg",
                "use_adamW",
                "drop_path_prob",
                "cosine_decay_restart",
                "softmax_dropout"
            ]
        },
        "architecture_parameters": {
            "type": "object",
            "properties": {
                "motifs": {
                    "type": "integer"
                },
                "normal_cells_per_motif": {
                    "type": "integer"
                },
                "concat_only_unused_blocks": {
                    "type": "boolean"
                },
                "multi_output": {
                    "type": "boolean"
                }
            },
            "required": [
                "motifs",
                "normal_cells_per_motif",
                "concat_only_unused_blocks",
                "multi_output"
            ]
        },
        "dataset": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "image_classification",
                        "time_series_classification"
                    ]
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "classes_count": {
                    "type": "integer"
                },
                "batch_size": {
                    "type": "integer"
                },
                "inference_batch_size": {
                    "type": "integer"
                },
                "validation_size": {
                    "oneOf": [
                        {
                            "type": "number"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "cache": {
                    "type": "boolean"
                },
                "folds": {
                    "type": "integer"
                },
                "samples": {
                    "oneOf": [
                        {
                            "type": "integer"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "balance_class_losses": {
                    "type": "boolean"
                },
                "resize": {
                    "type": "object",
                    "properties": {
                        "enabled": {
                            "type": "boolean"
                        },
                        "width": {
                            "type": "integer"
                        },
                        "height": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "enabled",
                        "width",
                        "height"
                    ]
                },
                "data_augmentation": {
                    "type": "object",
                    "properties": {
                        "enabled": {
                            "type": "boolean"
                        },
                        "perform_on_gpu": {
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "enabled",
                        "perform_on_gpu"
                    ]
                }
            },
            "required": [
                "type",
                "name",
                "path",
                "classes_count",
                "batch_size",
                "inference_batch_size",
                "validation_size",
                "cache",
                "folds",
                "samples",
                "balance_class_losses",
                "data_augmentation"
            ]
        },
        "others": {
            "type": "object",
            "properties": {
                "accuracy_predictor_ensemble_units": {
                    "type": "integer"
                },
                "predictions_batch_size": {
                    "type": "integer"
                },
                "save_children_weights": {
                    "type": "boolean"
                },
                "save_children_as_onnx": {
                    "type": "boolean"
                },
                "pnas_mode": {
                    "type": "boolean"
                },
                "train_strategy": {
                    "type": "string",
                    "enum": [
                        "CPU",
                        "GPU",
                        "TPU"
                    ]
                }
            },
            "required": [
                "accuracy_predictor_ensemble_units",
                "predictions_batch_size",
                "save_children_weights",
                "save_children_as_onnx",
                "pnas_mode",
                "train_strategy"
            ]
        }
    },
    "required": [
        "search_space",
        "search_strategy",
        "cnn_hp",
        "architecture_parameters",
        "dataset",
        "others"
    ]
}

=== AndreaFalanti/popnas/src/configs/run_ts.json
{
    "search_space": {
        "blocks": 5,
        "lookback_depth": 2,
        "operators": [
            "identity",
            "3 dconv",
            "7 dconv",
            "15 dconv",
            "3 conv",
            "7 conv",
            "15 conv",
            "2 maxpool",
            "2 avgpool"
        ]
    },
    "search_strategy": {
        "max_children": 256,
        "max_exploration_children": 16,
        "score_metric": "accuracy",
        "additional_pareto_objectives": ["time"]
    },
    "cnn_hp": {
        "epochs": 21,
        "learning_rate": 0.008,
        "filters": 24,
        "weight_reg": 5e-4,
        "use_adamW": true,
        "drop_path_prob": 0.0,
        "cosine_decay_restart": {
            "enabled": true,
            "period_in_epochs": 3,
            "t_mul": 2.0,
            "m_mul": 1.0,
            "alpha": 0.0
        },
        "softmax_dropout": 0.0
    },
    "architecture_parameters": {
        "motifs": 3,
        "normal_cells_per_motif": 2,
        "block_join_operator": "add",
        "lookback_reshape": true,
        "concat_only_unused_blocks": true,
        "multi_output": false
    },
    "dataset": {
        "type": "time_series_classification",
        "name": "custom-dataset",
        "path": "insert-path",
        "classes_count": 10,
        "batch_size": 64,
        "inference_batch_size": 16,
        "validation_size": 0.1,
        "cache": true,
        "folds": 1,
        "samples": null,
        "balance_class_losses": false,
        "normalize": false,
        "rescale": false,
        "data_augmentation": {
            "enabled": false,
            "perform_on_gpu": false
        }
    },
    "others": {
        "accuracy_predictor_ensemble_units": 5,
        "predictions_batch_size": 1024,
        "save_children_weights": false,
        "save_children_as_onnx": false,
        "pnas_mode": false,
        "train_strategy": "GPU"
    }
}
